GWOSC_KEYS = [
    'GPS',
    'catalog.shortName',
    'chi_eff',
    'chi_eff_lower',
    'chi_eff_unit',
    'chi_eff_upper',
    'chirp_mass',
    'chirp_mass_lower',
    'chirp_mass_source',
    'chirp_mass_source_lower',
    'chirp_mass_source_unit',
    'chirp_mass_source_upper',
    'chirp_mass_unit',
    'chirp_mass_upper',
    'commonName',
    'far',
    'far_lower',
    'far_unit',
    'far_upper',
    'final_mass_source',
    'final_mass_source_lower',
    'final_mass_source_unit',
    'final_mass_source_upper',
    'jsonurl',
    'luminosity_distance',
    'luminosity_distance_lower',
    'luminosity_distance_unit',
    'luminosity_distance_upper',
    'mass_1_source',
    'mass_1_source_lower',
    'mass_1_source_unit',
    'mass_1_source_upper',
    'mass_2_source',
    'mass_2_source_lower',
    'mass_2_source_unit',
    'mass_2_source_upper',
    'network_matched_filter_snr',
    'network_matched_filter_snr_lower',
    'network_matched_filter_snr_unit',
    'network_matched_filter_snr_upper',
    'redshift',
    'redshift_lower',
    'redshift_unit',
    'redshift_upper',
    'reference',
    'total_mass_source',
    'total_mass_source_lower',
    'total_mass_source_unit',
    'total_mass_source_upper',
    'version'
]

PARAMETERS = {
    'mass_1_source': '$m_1^{\\mathrm{source}}$',
    'mass_2_source': '$m_2^{\\mathrm{source}}$',
    'mass_ratio': '$q$',
    'a_1': '$a_1$',
    'a_2': '$a_2$',
    'cos_tilt_1': '$\\cos \\mathrm{tilt}_1$',
    'cos_tilt_2': '$\\cos \\mathrm{tilt}_2$',
    'phi_12': '$\\phi_{12}$',
    'phi_jl': '$\\phi_{JL}$',
    'luminosity_distance': '$d_L$',
    'redshift': '$z$',
    'spin_1x': '$\\mathrm{S}_{1x}$',
    'spin_1y': '$\\mathrm{S}_{1y}$',
    'spin_1z': '$\\mathrm{S}_{1z}$',
    'spin_2x': '$\\mathrm{S}_{2x}$',
    'spin_2y': '$\\mathrm{S}_{2y}$',
    'spin_2z': '$\\mathrm{S}_{2z}$',
    'ra': "$ra$",
    'dec': "$dec$",
    'incl': "$incl$",
    'geocent_time': "$t_{c}$",
}

REQUIRED_PARAMETERS = set([p for p in PARAMETERS.keys()])
